name: Create Tag then Trigger Stage Deploy

on:
  workflow_dispatch:
  pull_request:
    # Execute the action on closed (merged) PR.
    types: 
      - closed
    branches:
      - 'changeset-release/main'

jobs:
  trigger-create-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Trigger deploy workflow for stage
        run: |
          repo_owner="duynguyen-s1"
          repo_name="auto-deploy"
          event_type="trigger-create-tag" 
          tag=${{github.run_id}}
          commitId=${{github.sha}}
          environment="stage"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"tag\": \"$tag\", \"commitId\": \"$commitId\", \"environment\": \"$environment\" }}"