name: Create Tag then Trigger Stage Deploy

on:
  workflow_dispatch:
  pull_request_target:
    # Execute the action on closed (merged) PR.
    types: 
      - closed

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Get Tags
      id: tags
      run: |
        git fetch --tags
        echo "Tags fetched"      
    - name: Get Latest Release Tag
      run: |
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo $latest_tag
        next_tag = $(($latest_tag + 1))
        echo $next_tag
  trigger-create-tag:
    if: startsWith(github.head_ref, 'changeset-release/') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Trigger deploy workflow for stage
        run: |
          repo_owner="duynguyen-s1"
          repo_name="auto-deploy"
          event_type="trigger-create-tag" 
          tag=${{github.run_id}}
          commitId=${{github.sha}}
          environment="stage"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"tag\": \"$tag\", \"commitId\": \"$commitId\", \"environment\": \"$environment\" }}"