name: Create Tag then Trigger Stage Deploy

on:
  workflow_dispatch:
  # pull_request_target:
    # Execute the action on closed (merged) PR.
    # types: 
    #   - closed

jobs:
  trigger-create-tag:
    # if: startsWith(github.head_ref, 'changeset-release/') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger create-tag workflow
        run: |
          repo_owner="duynguyen-s1"
          repo_name="auto-deploy"
          event_type="trigger-create-tag" 
          commitId=${{github.sha}}

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"commitId\": \"$commitId\"}}"