name: Auto Create Tag

on:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit ID
        required: true
        type: string
      # tagname:
      #   description: Tag Name
      #   required: true
      #   type: string

  repository_dispatch:
    types: [trigger-create-tag]

env:
  # TAG: ${{ inputs.tagname || github.event.client_payload.tag}}
  COMMIT_ID: ${{ inputs.commit || github.event.client_payload.commitId }}
  ENVIRONMENT: ${{ github.event.client_payload.environment || 'stage'}}

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get previous tag
        id: prev-tag
        run: |
          git fetch --tags
          echo "prev-tag= $(git tag --sort=committerdate | tail -1)" >> $GITHUB_OUTPUT

      - name: Show previous tag
        run: echo ${{steps.prev-tag.outputs.prev-tag}}

      - name: Generate new tag
        uses: actions/github-script@v7
        id: generate-tag
        with:
          script: |
            let repoTag = '${{ steps.prev-tag.outputs.prev-tag }}';
            repoTag = repoTag.trim();

            const fullYear = new Date().getFullYear();
            const shortYear = new Date().toLocaleDateString("en", {year: "2-digit"});
            const week = 7 * 24 * 60 * 60 * 1000;
            const today = new Date(); // the month is 0-indexed
            today.setHours(01, 01, 01)

            // Get the first Wednesday of the year
            function getWednesday(d) {
              d = new Date(d);
              const day = d.getDay(),
                diff = d.getDate() - day + (day == 0 ? -4 : 3); // adjust when day is sunday
              return new Date(d.setDate(diff));
            }
            const firstWednesdayofYear = getWednesday(new Date(fullYear, 0, 1)); // the month is 0-indexed


            // Calculate the number of weeks between today and the first Wednesday of the year
            function getWeeksBetween(d1, d2) {
                return ((d2 - d1) / week) * -1;
            }

            const weeksBetween = getWeeksBetween(today, firstWednesdayofYear);

            function getCurrentSprint(weeksBetween) {
              const day = today.getDay(),
                sprint = Math.ceil(weeksBetween / 2);
              return sprint;
            }
            const currentSprint = getCurrentSprint(weeksBetween);
            let releaseNum = 1;
            let newTag = `${shortYear}.${currentSprint}.${releaseNum}`;

            while (newTag == repoTag) {
              releaseNum++;
              newTag = `${shortYear}.${currentSprint}.${releaseNum}`;
            }
            console.log({repoTag, newTag});
            return newTag;

      - name: Verify tag availability
        run: |
          TAG=${{steps.generate-tag.outputs.result}}
          if git show-ref --tags --verify --quiet "refs/tags/${TAG}"; then
            echo "Tag ${TAG} already exist"
          else
            echo "Tag ${TAG} is available"
          fi

      - run: git tag ${{steps.generate-tag.outputs.result}} $COMMIT_ID
      - run: git push origin ${{steps.generate-tag.outputs.result}}
  
  trigger-stage-deploy:
    needs: [tag]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy workflow for stage
        run: |
          repo_owner="duynguyen-s1"
          repo_name="auto-deploy"
          event_type="trigger-deploy" 
          tag=$TAG
          env=$ENVIRONMENT

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"tag\": \"$tag\", \"env\": \"$env\" }}"