name: Create Tag and Deploy

on:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit ID
        required: true
        type: string
      tagname:
        description: Tag Name
        required: true
        type: string

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git tag ${{ inputs.tagname }} ${{ inputs.commit }}
      - run: git push origin ${{ inputs.tagname }}
