name: Create Tag

on:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit ID
        required: true
        type: string
      tagname:
        description: Tag Name
        required: true
        type: string

  repository_dispatch:
    types: [trigger-create-tag]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git tag ${{ inputs.tagname || github.event.client_payload.tag}} ${{ inputs.commit || github.event.client_payload.commitId }}
      - run: git push origin ${{ inputs.tagname }}
  
  trigger-stage-deploy:
    needs: [tag]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy workflow for stage
        run: |
          repo_owner="duynguyen-s1"
          repo_name="auto-deploy"
          event_type="trigger-deploy" 
          tag=${{github.event.inputs.tagname}}
          env="duy"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"tag\": \"$tag\", \"env\": \"$env\" }}"