name: Pull Request

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: ["assigned", "opened", "synchronize", "reopened", "edited"]
  push:
    branches:
      - "changeset-release/main"

jobs:
  e2e-tests:
    environment: dev
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Environment variables
        uses: ./.github/actions/env
        with:
          vars: ${{ toJSON(vars) }}
      - name: Install Playwright browsers
        run: pnpm run playwright-browsers
      - name: Test
        run: pnpm run e2e-tests

  run-tests:
    environment: dev
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Environment variables
        uses: ./.github/actions/env
        with:
          vars: ${{ toJSON(vars) }}
      - name: Test
        run: pnpm run-tests:units:ci

  run-linters:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: Run code linters
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Lint
        run: pnpm lint

  run-typecheckers:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: Run typechecks
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Typecheck
        run: pnpm typecheck

  run-prettier:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: Run prettier formatting check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Check formatting
        run: pnpm format:check