name: Create Tag then Trigger Stage Deploy

on:
  workflow_dispatch:
  # pull_request_target:
    # Execute the action on closed (merged) PR.
    # types: 
    #   - closed

jobs:
  trigger-create-tag:
    # if: startsWith(github.head_ref, 'changeset-release/') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger create-tag workflow
        uses: ./.github/workflows/auto-create-tag.yml
        with:
          commit: ${{ github.sha }}
          tagname: ''
          env: ''